-- RLS Fix Migration
-- NOTE: The tables company_settings, count_verifications, inventory_adjustments,
-- and count_learning_data from 003_inventory_counts.sql were never created in this database.
-- No action needed — those permissive policies do not exist because the tables do not exist.
-- This file is kept as documentation only.
